blank_issues_enabled: false
contact_links:
  - name: Questions & Help ðŸ™‹
    url: https://github.com/ivodolenc/nuxt-lazysizes/discussions
    about: Please use Discussions for all additional questions or technical advices.
